<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNG5RqAg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNG5RqAg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNG5RqAg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNG5RqAg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNG5RqAg\App_KernelDevDebugContainer([
    'container.build_hash' => 'NG5RqAg',
    'container.build_id' => '2e4ff42b',
    'container.build_time' => 1712915360,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNG5RqAg');
